name: mirar
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3
  searchfield: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - shorebird.yaml
  uses-material-design: true
  fonts:
    - family: Halvar
      fonts:
        - asset: assets/fonts/HalvarBreit-Blk.ttf
