name: mirar
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter_bloc: ^8.1.4
  talker_flutter: ^4.1.3
  talker_dio_logger: ^4.1.3
  talker_bloc_logger: ^4.1.3
  go_router: ^14.3.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dio: ^5.2.0+1
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3
  searchfield: ^1.1.6
  shared_preferences: ^2.3.2
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  provider: ^6.1.2
  path_provider: ^2.1.5
  appmetrica_plugin: ^3.1.0
  rxdart: ^0.27.7
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  parse_server_sdk_flutter: ^8.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  freezed: ^2.5.2

flutter:
  generate: true
  assets:
    - shorebird.yaml
    - assets/icons/google.png

  uses-material-design: true
  fonts:
    - family: Halvar
      fonts:
        - asset: assets/fonts/HalvarBreit-Blk.ttf
